version: '3.8'
services:
  postgres:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nycmesh
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  nycmesh-node-visualizer:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nycmesh
      POSTGRES_HOST: nycmesh-node-visualizer-postgres-1
      POSTGRES_PORT: 5432
    command: npm run start

volumes:
  postgres_data:
