name: Link, format, and unit tests
on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier -check
        run: |
          npm ci
          npm run format

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run eslint
        run: |
          npm ci
          npm run lint

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start postgres
        run: |
          cp .env.staging .env
          docker compose up -d
      - name: Run unittest
        run: |
          npm ci
          npm run unittest
